from typing import Any

class _Validator:
    def __init__(
        self, schema: Any, *, registry: Registry | None = None, **kwargs: Any
    ) -> None: ...
    def is_valid(self, instance: Any) -> bool: ...

class Draft4Validator(_Validator): ...
class Draft6Validator(_Validator): ...
class Draft7Validator(_Validator): ...
class Draft201909Validator(_Validator): ...
class Draft202012Validator(_Validator): ...

class Registry:
    def __init__(
        self, resources: Any, *, draft: Any | None = None, retriever: Any | None = None
    ) -> None: ...

Draft4: Any
Draft6: Any
Draft7: Any
Draft201909: Any
Draft202012: Any
