from typing import Any

class _Validator:
    def __init__(self, schema: Any) -> None: ...
    def is_valid(self, instance: Any) -> bool: ...

class Draft4Validator(_Validator): ...
class Draft6Validator(_Validator): ...
class Draft7Validator(_Validator): ...
class Draft201909Validator(_Validator): ...
class Draft202012Validator(_Validator): ...
