from typing import Any, Protocol

class FSM(Protocol):
    initial: Any
    finals: set[Any]
    map: dict[Any, dict[Any, Any]]
    states: set[Any]
    def issubset(self, other: FSM) -> bool: ...
    def isdisjoint(self, other: FSM) -> bool: ...
    def equivalent(self, other: FSM) -> bool: ...

class Pattern(Protocol):
    def reduce(self) -> Pattern: ...
    def empty(self) -> bool: ...
    def everythingbut(self) -> Pattern: ...
    def difference(self, other: Pattern) -> Pattern: ...
    def to_fsm(self) -> FSM: ...
    def matches(self, value: str) -> bool: ...
    def __and__(self, other: Pattern) -> Pattern: ...
    def __or__(self, other: Pattern) -> Pattern: ...

def parse(pattern: str) -> Pattern: ...
