"""
Typed semantic IR package exports.
"""

from __future__ import annotations

from subschema.ir.constraints import (
    ArrayAnyOfItemSchemasConstraint,
    ArrayContainsConstraint,
    ArrayContainsFragmentConstraint,
    ArrayItemModelConstraint,
    ArrayItemValuesFragmentConstraint,
    ArrayLengthConstraint,
    ArrayTupleAnyOfDistributionConstraint,
    ArrayUniquenessConstraint,
    FiniteConstraint,
    NumericConstraint,
    ObjectClosedPropertiesConstraint,
    ObjectDependentRequiredConstraint,
    ObjectDependentSchemaPropertiesConstraint,
    ObjectDependentSchemaProperty,
    ObjectKeyValueConstraint,
    ObjectPresenceProductConstraint,
    ObjectPropertyCountBoundsConstraint,
    ObjectPropertyCountConstraint,
    ObjectPropertyNamesConstraint,
    ObjectPropertyValuesConstraint,
    StringLanguageConstraint,
    StringLengthConstraint,
    TypeConstraint,
)
from subschema.ir.evaluation import EvaluationFrontier
from subschema.ir.nodes import (
    ApplicatorKind,
    ApplicatorNode,
    LogicalSchemaIR,
    SchemaDocumentIR,
    SchemaNode,
    UnsupportedNode,
)
from subschema.ir.references import (
    DynamicReferenceSemantics,
    RecursiveReferenceFact,
    RecursiveReferenceGuard,
    RecursiveReferenceObligation,
    RecursiveReferencePolarity,
    ReferenceSemantics,
    ReferenceUnsupportedFact,
    StaticReferenceSemantics,
)
from subschema.ir.semantics import (
    ApplicatorSemantics,
    ArraySelectorCandidate,
    ArraySemantics,
    AssertionAtom,
    DomainFactInfo,
    DomainFactStatus,
    EvaluationSemantics,
    IRAssertionKind,
    ObjectSelectorCandidate,
    ObjectSemantics,
    ScalarSemantics,
    SchemaSemantics,
    TaggedBranch,
    TaggedOneOf,
    VocabularySemantics,
)
from subschema.ir.terms import SchemaNodeRef, SchemaTerm

__all__ = [
    "AssertionAtom",
    "ApplicatorKind",
    "ApplicatorNode",
    "ApplicatorSemantics",
    "ArrayAnyOfItemSchemasConstraint",
    "ArrayContainsConstraint",
    "ArrayContainsFragmentConstraint",
    "ArrayItemModelConstraint",
    "ArrayItemValuesFragmentConstraint",
    "ArrayLengthConstraint",
    "ArraySelectorCandidate",
    "ArraySemantics",
    "ArrayTupleAnyOfDistributionConstraint",
    "ArrayUniquenessConstraint",
    "DomainFactInfo",
    "DomainFactStatus",
    "DynamicReferenceSemantics",
    "EvaluationFrontier",
    "EvaluationSemantics",
    "FiniteConstraint",
    "IRAssertionKind",
    "LogicalSchemaIR",
    "NumericConstraint",
    "ObjectClosedPropertiesConstraint",
    "ObjectDependentRequiredConstraint",
    "ObjectDependentSchemaPropertiesConstraint",
    "ObjectDependentSchemaProperty",
    "ObjectKeyValueConstraint",
    "ObjectPresenceProductConstraint",
    "ObjectPropertyCountBoundsConstraint",
    "ObjectPropertyCountConstraint",
    "ObjectPropertyNamesConstraint",
    "ObjectPropertyValuesConstraint",
    "ObjectSelectorCandidate",
    "ObjectSemantics",
    "RecursiveReferenceFact",
    "RecursiveReferenceGuard",
    "RecursiveReferenceObligation",
    "RecursiveReferencePolarity",
    "ReferenceSemantics",
    "ReferenceUnsupportedFact",
    "ScalarSemantics",
    "SchemaDocumentIR",
    "SchemaNode",
    "SchemaNodeRef",
    "SchemaSemantics",
    "SchemaTerm",
    "StaticReferenceSemantics",
    "StringLanguageConstraint",
    "StringLengthConstraint",
    "TaggedBranch",
    "TaggedOneOf",
    "TypeConstraint",
    "UnsupportedNode",
    "VocabularySemantics",
]
