from fractions import Fraction
from typing import Any

class Z3Exception(Exception): ...

class ExprRef: ...
class BoolRef(ExprRef): ...
class ArithRef(ExprRef): ...
class IntNumRef(ArithRef):
    def as_long(self) -> int: ...
class RatNumRef(ArithRef):
    def as_fraction(self) -> Fraction: ...
    def numerator_as_long(self) -> int: ...
    def denominator_as_long(self) -> int: ...
    def as_decimal(self, precision: int) -> str: ...

class CheckSatResult:
    def __eq__(self, other: object) -> bool: ...

class ModelRef:
    def evaluate(
        self, expression: ExprRef, *, model_completion: bool = False
    ) -> Any: ...

class Solver:
    def __init__(self) -> None: ...
    def add(self, *constraints: ExprRef) -> None: ...
    def set(self, **kwargs: Any) -> None: ...
    def check(self) -> CheckSatResult: ...
    def reason_unknown(self) -> str: ...
    def model(self) -> ModelRef: ...

sat: CheckSatResult
unsat: CheckSatResult
unknown: CheckSatResult

def SolverFor(logic: str) -> Solver: ...
def Bool(name: str) -> BoolRef: ...
def Int(name: str) -> ArithRef: ...
def Real(name: str) -> ArithRef: ...
def BoolVal(value: bool) -> BoolRef: ...
def And(*constraints: ExprRef) -> BoolRef: ...
def Or(*constraints: ExprRef) -> BoolRef: ...
def Not(constraint: ExprRef) -> BoolRef: ...
def IsInt(value: ExprRef) -> BoolRef: ...
def Implies(lhs: ExprRef, rhs: ExprRef) -> BoolRef: ...
def PbGe(terms: list[tuple[ExprRef, int]], minimum: int) -> BoolRef: ...
def PbLe(terms: list[tuple[ExprRef, int]], maximum: int) -> BoolRef: ...
def PbEq(terms: list[tuple[ExprRef, int]], count: int) -> BoolRef: ...
def Sum(values: list[ExprRef | int]) -> ArithRef: ...
def If(condition: ExprRef, then_value: int, else_value: int) -> ArithRef: ...
def Q(numerator: int, denominator: int) -> ArithRef: ...
def is_true(value: Any) -> bool: ...
